.TH NEKO 1 "May 1, 2017" ""
.SH NAME
neko \- Neko virtual machine.
.SH SYNOPSIS
.B neko
\fIfile.n\fR
.SH DESCRIPTION
.B neko
is a command-line tool for running Neko bytecode.
.PP
Neko programs are usually written in Haxe, although Neko itself
also comes with a high-level dynamically typed programming language of the same name (Neko),
and NekoML, which is a high-order functional language with type inference.
.SH AUTHOR
Neko is currently maintained by the Haxe Foundation.
It was originally written by Nicolas Cannasse for Motion-Twin.
.SH SEE ALSO
.BR "nekoc" (1),
.BR "nekoml" (1),
.BR "nekotools" (1).
.SH WEB
.IR "http://nekovm.org" .
